/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

public class FrmPRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form FrmPRINCIPAL
     */
    public FrmPRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemRegistrarCategoria = new javax.swing.JMenuItem();
        mnuItemRegistrarProducto = new javax.swing.JMenuItem();
        mnuItemRegistrarCliente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItemConsultarProductos = new javax.swing.JMenuItem();
        mnuItemConsultarClientes = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuItemRealizarPedido = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuItemSalir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("principal");
        setBackground(new java.awt.Color(0, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));

        jMenu1.setText("MANTENIMIENTO");

        mnuItemRegistrarCategoria.setText("Registrar Categoria");
        mnuItemRegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistrarCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemRegistrarCategoria);

        mnuItemRegistrarProducto.setText("Registrar Producto");
        mnuItemRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistrarProductoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemRegistrarProducto);

        mnuItemRegistrarCliente.setText("Registrar Cliente");
        mnuItemRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistrarClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemRegistrarCliente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CONSULTA");

        mnuItemConsultarProductos.setText("Consultar Productos");
        mnuItemConsultarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultarProductosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemConsultarProductos);

        mnuItemConsultarClientes.setText("Consultar Clientes");
        mnuItemConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemConsultarClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItemConsultarClientes);

        jMenuBar1.add(jMenu2);

        jMenu6.setBackground(new java.awt.Color(0, 153, 204));
        jMenu6.setText("PEDIDOS");

        mnuItemRealizarPedido.setText("Realizar Pedido");
        mnuItemRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRealizarPedidoActionPerformed(evt);
            }
        });
        jMenu6.add(mnuItemRealizarPedido);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("SALIR");

        mnuItemSalir.setText("salir");
        mnuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSalirActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistrarProductoActionPerformed
        // TODO add your handling code here:
        FrmRegistrarProducto oFrmRegistrarProducto = new FrmRegistrarProducto(this, true);
        oFrmRegistrarProducto.setLocationRelativeTo(null);
        oFrmRegistrarProducto.setVisible(true);
                
    }//GEN-LAST:event_mnuItemRegistrarProductoActionPerformed

    private void mnuItemRegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistrarCategoriaActionPerformed
        // TODO add your handling code here:
        FrmRegistrarCategoria oFrmRegistrarCategoria = new FrmRegistrarCategoria(this, true);
        oFrmRegistrarCategoria.setLocationRelativeTo(null);
        oFrmRegistrarCategoria.setVisible(true);
        
    }//GEN-LAST:event_mnuItemRegistrarCategoriaActionPerformed

    private void mnuItemConsultarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultarProductosActionPerformed
        // TODO add your handling code here:
        FrmConsultaProducto oConsultarProducto = new FrmConsultaProducto(this, true);
        oConsultarProducto.setLocationRelativeTo(null);
        oConsultarProducto.setVisible(true);
        
    }//GEN-LAST:event_mnuItemConsultarProductosActionPerformed

    private void mnuItemRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistrarClienteActionPerformed
        // TODO add your handling code here:
        FrmRegistrarCliente oRegistrarCliente = new FrmRegistrarCliente(this, true);
        oRegistrarCliente.setLocationRelativeTo(null);
        oRegistrarCliente.setVisible(true);
    }//GEN-LAST:event_mnuItemRegistrarClienteActionPerformed

    private void mnuItemConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemConsultarClientesActionPerformed
        // TODO add your handling code here:
        FrmConsultaCliente oConsultaCliente = new FrmConsultaCliente(this, true);
        oConsultaCliente.setLocationRelativeTo(null);
        oConsultaCliente.setVisible(true);
    }//GEN-LAST:event_mnuItemConsultarClientesActionPerformed

    private void mnuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuItemSalirActionPerformed

    private void mnuItemRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRealizarPedidoActionPerformed
        // TODO add your handling code here:
        FrmRealizarPedido oPedido = new FrmRealizarPedido(this, true);
        oPedido.setVisible(true);
        oPedido.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuItemRealizarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPRINCIPAL().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuItemConsultarClientes;
    private javax.swing.JMenuItem mnuItemConsultarProductos;
    private javax.swing.JMenuItem mnuItemRealizarPedido;
    private javax.swing.JMenuItem mnuItemRegistrarCategoria;
    private javax.swing.JMenuItem mnuItemRegistrarCliente;
    private javax.swing.JMenuItem mnuItemRegistrarProducto;
    private javax.swing.JMenuItem mnuItemSalir;
    // End of variables declaration//GEN-END:variables
}
