/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.model.beans.Categoria;
import com.model.beans.Producto;
import com.model.logic.CategoriaLogic;
import com.model.logic.ProductoLogic;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class FrmRegistrarProducto extends javax.swing.JDialog {

    private String codigo;
    private String nombre;
    private double costo;
    private double precio;
    private int stock;
    private Categoria oCategoria;
    int num = 1;
    private Producto oProducto;
    private File fichero; // Ruta del fichero a modificar
    private JFrame ventanaPadre; // Ventana anterior de trabajo
    private LinkedList productosGuardar = new LinkedList();// Contraseñas a guardar en el archivo
    
    /**
     * Creates new form FrmRegistrarProducto
     */
    public FrmRegistrarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //cargar();
        CargarCombo();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        cboCategoria = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("datos"));

        jLabel1.setText("codigo");

        jLabel2.setText("nombre");

        jLabel3.setText("precio");

        jLabel4.setText("stock");

        jLabel5.setText("costo");

        jLabel6.setText("categoria");

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio)
                                    .addComponent(txtStock, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                .addGap(51, 51, 51)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(txtNombre))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("lista de Productos"));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("mantenimiento"));

        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/insertar.gif"))); // NOI18N
        btnInsertar.setText("insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/modificar.png"))); // NOI18N
        btnModificar.setText("modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar.gif"))); // NOI18N
        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnInsertar)
                .addGap(18, 18, 18)
                .addComponent(btnModificar)
                .addGap(30, 30, 30)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(29, 29, 29)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:

        codigo = txtCodigo.getText();
        nombre = txtNombre.getText();
        costo = Double.parseDouble(txtCosto.getText());
        precio = Double.parseDouble(txtPrecio.getText());
        stock = Integer.parseInt(txtStock.getText());
        oCategoria = (Categoria) cboCategoria.getSelectedItem();

        Producto oProducto = new Producto();

        oProducto.setIdProducto(codigo);
        oProducto.setNombre(nombre);
        oProducto.setCosto(costo);
        oProducto.setPrecio(precio);
        oProducto.setStock(stock);
        oProducto.setoCategoria(oCategoria);

        if (ProductoLogic.insertarProducto(oProducto)) {
            System.out.println("se inserto correptamente");
            JOptionPane.showMessageDialog(this, "insercion correpta", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            num++;
            txtCodigo.setText("P00" + num);
            txtNombre.setText("");
            txtCosto.setText("");
            txtPrecio.setText("");
            txtStock.setText("");

        } else {
            System.out.println("no pudo se insertado");
            JOptionPane.showMessageDialog(this, "no pudo ser insertado", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);

        }
        String nuevoProducto;
        nuevoProducto = codigo + " " + nombre + " "+costo+" "+ precio+" "+ stock+" "+ oCategoria+" \n";
        productosGuardar.add(nuevoProducto);
        modeloTabla = ProductoLogic.obtenerModeloTabla();
        tblProductos.setModel(modeloTabla);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        codigo = txtCodigo.getText();
        nombre = txtNombre.getText();
        costo = Double.parseDouble(txtCosto.getText());
        precio = Double.parseDouble(txtPrecio.getText());
        stock = Integer.parseInt(txtStock.getText());
        oCategoria = (Categoria) cboCategoria.getSelectedItem();

        Producto oProducto = new Producto();

        oProducto.setIdProducto(codigo);
        oProducto.setNombre(nombre);
        oProducto.setCosto(costo);
        oProducto.setPrecio(precio);
        oProducto.setStock(stock);
        oProducto.setoCategoria(oCategoria);

        if (ProductoLogic.modificarProducto(oProducto)) {
            System.out.println("se modifico correptamente");
            JOptionPane.showMessageDialog(this, "modificacion correpta", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            txtCodigo.setText("P00" + num);
            txtNombre.setText("");
            txtCosto.setText("");
            txtPrecio.setText("");
            txtStock.setText("");

        } else {
            System.out.println("no pudo ser modificado");
            JOptionPane.showMessageDialog(this, "no pudo ser modificado ", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);

        }
        int indice;
        indice = this.tblProductos.getSelectedRow();
        String nuevoProducto;
        nuevoProducto = codigo + " " + nombre + " "+costo+" "+ precio+" "+ stock+" "+ oCategoria+" \n";
        productosGuardar.set(indice,nuevoProducto);
        
        modeloTabla = ProductoLogic.obtenerModeloTabla();
        tblProductos.setModel(modeloTabla);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        codigo = txtCodigo.getText();
        nombre = txtNombre.getText();
        costo = Double.parseDouble(txtCosto.getText());
        precio = Double.parseDouble(txtPrecio.getText());
        stock = Integer.parseInt(txtStock.getText());
        oCategoria = (Categoria) cboCategoria.getSelectedItem();

        Producto oProducto = new Producto();

        oProducto.setIdProducto(codigo);
        oProducto.setNombre(nombre);
        oProducto.setCosto(costo);
        oProducto.setPrecio(precio);
        oProducto.setStock(stock);
        oProducto.setoCategoria(oCategoria);

        if (ProductoLogic.eliminarProducto(oProducto)) {
            System.out.println("eliminacion correpta");
            JOptionPane.showMessageDialog(this, "eliminacion correpta", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            txtCodigo.setText("P00" + num);
            txtNombre.setText("");
            txtCosto.setText("");
            txtPrecio.setText("");
            txtStock.setText("");

        } else {
            System.out.println("no pudo ser eliminado");
            JOptionPane.showMessageDialog(this, "no pudo ser eliminado", "MENSAJE", JOptionPane.INFORMATION_MESSAGE);

        }
        int indice;
        indice = this.tblProductos.getSelectedRow();     
        productosGuardar.remove(indice);
        
        modeloTabla = ProductoLogic.obtenerModeloTabla();
        tblProductos.setModel(modeloTabla);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int indice;
        indice = tblProductos.getSelectedRow();
        txtCodigo.setText((String) (tblProductos.getValueAt(indice, 0)));
        txtNombre.setText((String) (tblProductos.getValueAt(indice, 1)));
        txtCosto.setText("" + tblProductos.getValueAt(indice, 2));
        txtPrecio.setText("" + tblProductos.getValueAt(indice, 3));
        txtStock.setText("" + tblProductos.getValueAt(indice, 4));
        Categoria oCategoria;
        oCategoria = (Categoria) tblProductos.getValueAt(indice, 5);      


    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        //FrmConsultaProducto oConsultaProducto = new FrmConsultaProducto(this, true);
        FrmConsultaProducto oConsultaProducto = new FrmConsultaProducto(null, true);
        oConsultaProducto.setLocationRelativeTo(null);
        oConsultaProducto.setVisible(true);
        oProducto = oConsultaProducto.productoSeleccionado();
        txtCodigo.setText(oProducto.getIdProducto());
        txtNombre.setText(oProducto.getNombre());
        txtCosto.setText(""+oProducto.getCosto());
        txtPrecio.setText(""+oProducto.getPrecio());
        txtStock.setText(""+oProducto.getStock());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        BufferedWriter writer; //Para escribir en el fichero

        if (fichero == null) {
            //Activamos el filtro para que nos muestre, por defecto, los archivos de texto
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto", "txt");
            JFileChooser fileChooserGuardar = new JFileChooser();
            fileChooserGuardar.setFileFilter(filtro);
            fileChooserGuardar.setDialogTitle("Guardar");
            int seleccion = fileChooserGuardar.showSaveDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = fileChooserGuardar.getSelectedFile();
                fileChooserGuardar.setFileSelectionMode(JFileChooser.FILES_ONLY);
                try {
                    writer = new BufferedWriter(new FileWriter(fichero + ".txt")); // Ponemos .txt para darle extension al archivo que creamos
                    while (!productosGuardar.isEmpty()) {
                        writer.write(productosGuardar.poll().toString());
                        writer.newLine();
                    }
                    writer.flush();
                    writer.close();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error guardar archivo", JOptionPane.ERROR_MESSAGE);
                }

                JOptionPane.showMessageDialog(this, "El fichero de texto se ha guardado correctamente con los datos introducidos");
            }
        } else if (!(fichero == null)) // Añadimos al fichero existente
        {
            try {
                writer = new BufferedWriter(new FileWriter(fichero, true));
                while (!productosGuardar.isEmpty()) {
                    writer.write(productosGuardar.poll().toString());
                    writer.newLine();
                }
                writer.flush();
                writer.close();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo", "Error guardar archivo", JOptionPane.ERROR_MESSAGE);
            }
            JOptionPane.showMessageDialog(this, "El fichero de texto se ha guardado correctamente con los datos introducidos");
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: Error al guardar", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
        }

        // Volvemos al menu principal
        this.setVisible(false);
        ventanaPadre.setVisible(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void CargarCombo() {

        modeloCombo = CategoriaLogic.obtenerModeloCombo();
        cboCategoria.setModel(modeloCombo);
    }

    public void CargarTabla() {
        modeloTabla = ProductoLogic.obtenerModeloTabla();
        tblProductos.setModel(modeloTabla);

    }

    public void cargar() {

        Categoria oCategoria1 = new Categoria();
        oCategoria1.setIdCategoria("C001");
        oCategoria1.setNombre("ABARROTES");

        Categoria oCategoria2 = new Categoria();
        oCategoria2.setIdCategoria("C002");
        oCategoria2.setNombre("LIMPIEZA");

        Categoria oCategoria3 = new Categoria();
        oCategoria3.setIdCategoria("C003");
        oCategoria3.setNombre("ELECTRO");


        Producto oProducto1 = new Producto();
        oProducto1.setIdProducto("P001");
        oProducto1.setNombre("GALLETA");
        oProducto1.setCosto(0.50);
        oProducto1.setPrecio(0.80);
        oProducto1.setStock(100);
        oProducto1.setoCategoria(oCategoria1);

        Producto oProducto2 = new Producto();
        oProducto2.setIdProducto("P002");
        oProducto2.setNombre("CHOCOLATE");
        oProducto2.setCosto(1.00);
        oProducto2.setPrecio(1.5);
        oProducto2.setStock(100);
        oProducto2.setoCategoria(oCategoria1);

        Producto oProducto3 = new Producto();
        oProducto3.setIdProducto("P003");
        oProducto3.setNombre("CARAMELO");
        oProducto3.setCosto(0.05);
        oProducto3.setPrecio(0.2);
        oProducto3.setStock(1000);
        oProducto3.setoCategoria(oCategoria1);

        Producto oProducto4 = new Producto();
        oProducto4.setIdProducto("P004");
        oProducto4.setNombre("CHICLE");
        oProducto4.setCosto(0.05);
        oProducto4.setPrecio(0.25);
        oProducto4.setStock(1000);
        oProducto4.setoCategoria(oCategoria1);

        Producto oProducto5 = new Producto();
        oProducto5.setIdProducto("P005");
        oProducto5.setNombre("YOGURT");
        oProducto5.setCosto(4.60);
        oProducto5.setPrecio(5.50);
        oProducto5.setStock(50);
        oProducto5.setoCategoria(oCategoria1);

        Producto oProducto6 = new Producto();
        oProducto6.setIdProducto("P006");
        oProducto6.setNombre("CEPILLO");
        oProducto6.setCosto(2.00);
        oProducto6.setPrecio(3.80);
        oProducto6.setStock(150);
        oProducto6.setoCategoria(oCategoria2);

        Producto oProducto7 = new Producto();
        oProducto7.setIdProducto("P007");
        oProducto7.setNombre("PASTA DENTAL");
        oProducto7.setCosto(3.50);
        oProducto7.setPrecio(5.80);
        oProducto7.setStock(80);
        oProducto7.setoCategoria(oCategoria2);

        Producto oProducto8 = new Producto();
        oProducto8.setIdProducto("P008");
        oProducto8.setNombre("ENJUAGUE BUCAL");
        oProducto8.setCosto(9.50);
        oProducto8.setPrecio(15.00);
        oProducto8.setStock(10);
        oProducto8.setoCategoria(oCategoria2);


        Producto oProducto9 = new Producto();
        oProducto9.setIdProducto("P009");
        oProducto9.setNombre("ILO DENTAL");
        oProducto9.setCosto(0.50);
        oProducto9.setPrecio(0.80);
        oProducto9.setStock(20);
        oProducto9.setoCategoria(oCategoria2);

        Producto oProducto10 = new Producto();
        oProducto10.setIdProducto("P0010");
        oProducto10.setNombre("JABON");
        oProducto10.setCosto(3.50);
        oProducto10.setPrecio(4.80);
        oProducto10.setStock(200);
        oProducto10.setoCategoria(oCategoria2);

        Producto oProducto11 = new Producto();
        oProducto11.setIdProducto("P0011");
        oProducto11.setNombre("COCINA");
        oProducto11.setCosto(350.50);
        oProducto11.setPrecio(500.00);
        oProducto11.setStock(5);
        oProducto11.setoCategoria(oCategoria3);

        Producto oProducto12 = new Producto();
        oProducto12.setIdProducto("P0012");
        oProducto12.setNombre("REFRIGERADORA");
        oProducto12.setCosto(1000);
        oProducto12.setPrecio(5000);
        oProducto12.setStock(2);
        oProducto12.setoCategoria(oCategoria3);

        Producto oProducto13 = new Producto();
        oProducto13.setIdProducto("P0013");
        oProducto13.setNombre("COCINA N2");
        oProducto13.setCosto(500);
        oProducto13.setPrecio(800);
        oProducto13.setStock(3);
        oProducto13.setoCategoria(oCategoria3);

        Producto oProducto14 = new Producto();
        oProducto14.setIdProducto("P0014");
        oProducto14.setNombre("MICROONDAS");
        oProducto14.setCosto(150.00);
        oProducto14.setPrecio(190.80);
        oProducto14.setStock(10);
        oProducto14.setoCategoria(oCategoria3);

        Producto oProducto15 = new Producto();
        oProducto15.setIdProducto("P0015");
        oProducto15.setNombre("OLLA ARROCERA");
        oProducto15.setCosto(25.50);
        oProducto15.setPrecio(48.80);
        oProducto15.setStock(10);
        oProducto15.setoCategoria(oCategoria3);

        ProductoLogic.insertarProducto(oProducto1);
        ProductoLogic.insertarProducto(oProducto2);
        ProductoLogic.insertarProducto(oProducto3);
        ProductoLogic.insertarProducto(oProducto4);
        ProductoLogic.insertarProducto(oProducto5);
        ProductoLogic.insertarProducto(oProducto6);
        ProductoLogic.insertarProducto(oProducto7);
        ProductoLogic.insertarProducto(oProducto8);
        ProductoLogic.insertarProducto(oProducto9);
        ProductoLogic.insertarProducto(oProducto10);
        ProductoLogic.insertarProducto(oProducto11);
        ProductoLogic.insertarProducto(oProducto12);
        ProductoLogic.insertarProducto(oProducto13);
        ProductoLogic.insertarProducto(oProducto14);
        ProductoLogic.insertarProducto(oProducto15);
        num = num + 15;

        modeloTabla = CategoriaLogic.obtenerModeloTabla();
        tblProductos.setModel(modeloTabla);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarProducto dialog = new FrmRegistrarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modeloTabla;
    private DefaultComboBoxModel modeloCombo;

}
